import { z } from "zod";

export const operationTypes = [
  "importPsdSourceAsset",
  "importPsdLayerMaterialization",
  "importPsdLayerMaterializationBatch",
  "importPsdStructuralScaffold",
  "importSplitPngSourceAsset",
  "createDrawable",
  "updateDrawable",
  "createPart",
  "updatePart",
  "deletePart",
  "moveStructureChild",
  "setDrawablePart",
  "setDrawableTexture",
  "generateMesh",
  "moveMeshVertex",
  "addMeshVertex",
  "removeMeshVertex",
  "addMeshTriangle",
  "removeMeshTriangle",
  "moveMeshUvPoint",
  "createParameter",
  "updateParameter",
  "deleteParameter",
  "addKeyform",
  "editKeyformKey",
  "addKeyformGrid2d",
  "createDynamicsGroup",
  "updateDynamicsGroup",
  "deleteDynamicsGroup",
  "createRotation2dRigControl",
  "createWarpLattice2dRigControl",
  "createWarpDeformer",
  "bindRigControlChild",
  "moveDrawableRigControlBinding",
  "reparentRigControl",
  "updateRigControl",
  "deleteRigControl",
  "setMaskRelation",
  "setDrawOrder",
  "setRuntimeVisibility",
  "setRightsMetadata",
  "applyTextureAtlasPreview",
  "createVariantGroup",
  "updateVariantGroup",
  "deleteVariantGroup",
  "createVariant",
  "updateVariant",
  "deleteVariant",
  "addVariantTargetDrawable",
  "removeVariantTargetDrawable",
  "setVariantMembership",
  "setVariantDefaultActiveSelection"
] as const;

export const OperationTypeSchema = z.enum(operationTypes);
export type OperationType = z.infer<typeof OperationTypeSchema>;
