import { z } from "zod";

export const operationTypes = [
  "importPsdSourceAsset",
  "importPsdLayerMaterialization",
  "importPsdLayerMaterializationBatch",
  "importPsdStructuralScaffold",
  "importSplitPngSourceAsset",
  "createDrawable",
  "updateDrawable",
  "createPart",
  "updatePart",
  "deletePart",
  "moveStructureChild",
  "setDrawablePart",
  "setDrawableTexture",
  "generateMesh",
  "moveMeshVertex",
  "addMeshVertex",
  "removeMeshVertex",
  "addMeshTriangle",
  "removeMeshTriangle",
  "moveMeshUvPoint",
  "createParameter",
  "updateParameter",
  "deleteParameter",
  "addKeyform",
  "editKeyformKey",
  "addKeyformGrid2d",
  "createDynamicsGroup",
  "updateDynamicsGroup",
  "deleteDynamicsGroup",
  "createRotation2dRigControl",
  "createWarpLattice2dRigControl",
  "createWarpDeformer",
  "bindRigControlChild",
  "moveDrawableRigControlBinding",
  "reparentRigControl",
  "updateRigControl",
  "setMaskRelation",
  "setDrawOrder",
  "setRuntimeVisibility",
  "setRightsMetadata"
] as const;

export const OperationTypeSchema = z.enum(operationTypes);
export type OperationType = z.infer<typeof OperationTypeSchema>;
