export const runtimePlayerPerformanceDiagnosticsVersion =
  "runtime-player-performance-diagnostics-v1" as const;

export type RuntimePlayerRuntimeCoreProfilingMode = "disabled" | "deep";

export type RuntimePlayerStageRenderMetricsSnapshot = {
  readonly renderCount: number;
  readonly scheduledRenderCount: number;
  readonly immediateRenderCount: number;
  readonly liveFrameMessageCount: number;
  readonly stageViewTransformMessageCount: number;
  readonly stageDisplayTransformMessageCount: number;
  readonly duplicateTransformSkipCount: number;
  readonly coalescedLiveFrameCount: number;
  readonly lastRafDeltaMs: number | null;
  readonly rafDeltaSampleCount: number;
  readonly lastRenderDurationMs: number | null;
  readonly renderDurationSampleCount: number;
  readonly lastLiveRenderInputEvaluationDurationMs?: number | null;
  readonly liveRenderInputEvaluationDurationSampleCount?: number;
  readonly evaluationCacheHitCount?: number;
  readonly evaluationCacheMissCount?: number;
  readonly evaluationCacheInvalidationCount?: number;
  readonly lastRuntimeCoreEvaluationDurationMs?: number | null;
  readonly runtimeCoreEvaluationDurationSampleCount?: number;
  readonly lastRuntimeCoreInputValidationDurationMs?: number | null;
  readonly runtimeCoreInputValidationDurationSampleCount?: number;
  readonly lastRuntimeCoreStateCompatibilityDurationMs?: number | null;
  readonly runtimeCoreStateCompatibilityDurationSampleCount?: number;
  readonly lastRuntimeCoreDynamicsEvaluationDurationMs?: number | null;
  readonly runtimeCoreDynamicsEvaluationDurationSampleCount?: number;
  readonly lastRuntimeCoreSnapshotCreationDurationMs?: number | null;
  readonly runtimeCoreSnapshotCreationDurationSampleCount?: number;
  readonly lastRuntimeCoreParameterResolutionDurationMs?: number | null;
  readonly runtimeCoreParameterResolutionDurationSampleCount?: number;
  readonly lastRuntimeCoreKeyformSamplingDurationMs?: number | null;
  readonly runtimeCoreKeyformSamplingDurationSampleCount?: number;
  readonly lastRuntimeCoreKeyformApplicationDurationMs?: number | null;
  readonly runtimeCoreKeyformApplicationDurationSampleCount?: number;
  readonly lastRuntimeCoreDeformerHierarchyEvaluationDurationMs?: number | null;
  readonly runtimeCoreDeformerHierarchyEvaluationDurationSampleCount?: number;
  readonly lastRuntimeCoreWarpDeformerVertexTransformDurationMs?: number | null;
  readonly runtimeCoreWarpDeformerVertexTransformDurationSampleCount?: number;
  readonly lastRuntimeCoreRotationDeformerVertexTransformDurationMs?: number | null;
  readonly runtimeCoreRotationDeformerVertexTransformDurationSampleCount?: number;
  readonly lastRuntimeCoreDrawableSnapshotCreationDurationMs?: number | null;
  readonly runtimeCoreDrawableSnapshotCreationDurationSampleCount?: number;
  readonly lastRuntimeCoreVisibilityDrawOrderEvaluationDurationMs?: number | null;
  readonly runtimeCoreVisibilityDrawOrderEvaluationDurationSampleCount?: number;
  readonly lastRuntimeCoreMaskEvaluationDurationMs?: number | null;
  readonly runtimeCoreMaskEvaluationDurationSampleCount?: number;
  readonly lastRuntimeCoreSnapshotValidationDurationMs?: number | null;
  readonly runtimeCoreSnapshotValidationDurationSampleCount?: number;
  readonly lastPoseEvaluationDurationMs?: number | null;
  readonly poseEvaluationDurationSampleCount?: number;
  readonly lastSnapshotToRenderDrawableDurationMs?: number | null;
  readonly snapshotToRenderDrawableDurationSampleCount?: number;
  readonly lastRenderInputSceneBuildDurationMs?: number | null;
  readonly renderInputSceneBuildDurationSampleCount?: number;
  readonly lastRenderInputScaffoldBuildDurationMs?: number | null;
  readonly renderInputScaffoldBuildDurationSampleCount?: number;
  readonly lastRenderInputClippingBuildDurationMs?: number | null;
  readonly renderInputClippingBuildDurationSampleCount?: number;
  readonly lastScheduledFrameDurationMs?: number | null;
  readonly scheduledFrameDurationSampleCount?: number;
  readonly canvasWidth: number;
  readonly canvasHeight: number;
  readonly devicePixelRatio: number;
};
