export const runtimePlayerPerformanceDiagnosticsVersion =
  "runtime-player-performance-diagnostics-v1" as const;

export type RuntimePlayerStageRenderMetricsSnapshot = {
  readonly renderCount: number;
  readonly scheduledRenderCount: number;
  readonly immediateRenderCount: number;
  readonly liveFrameMessageCount: number;
  readonly stageViewTransformMessageCount: number;
  readonly stageDisplayTransformMessageCount: number;
  readonly duplicateTransformSkipCount: number;
  readonly coalescedLiveFrameCount: number;
  readonly lastRafDeltaMs: number | null;
  readonly rafDeltaSampleCount: number;
  readonly lastRenderDurationMs: number | null;
  readonly renderDurationSampleCount: number;
  readonly lastLiveRenderInputEvaluationDurationMs?: number | null;
  readonly liveRenderInputEvaluationDurationSampleCount?: number;
  readonly evaluationCacheHitCount?: number;
  readonly evaluationCacheMissCount?: number;
  readonly evaluationCacheInvalidationCount?: number;
  readonly compiledEvaluatorFrameCount?: number;
  readonly compiledRenderFrameCount?: number;
  readonly transientCompileCount?: number;
  readonly transientInstanceCount?: number;
  readonly publicSnapshotMaterializationCount?: number;
  readonly runtimeModelInstanceCacheHitCount?: number;
  readonly runtimeModelInstanceCacheMissCount?: number;
  readonly runtimeModelInstanceCacheInvalidationCount?: number;
  readonly lastRuntimeModelCompileDurationMs?: number | null;
  readonly runtimeModelCompileDurationSampleCount?: number;
  readonly lastPoseEvaluationDurationMs?: number | null;
  readonly poseEvaluationDurationSampleCount?: number;
  readonly lastSnapshotToRenderDrawableDurationMs?: number | null;
  readonly snapshotToRenderDrawableDurationSampleCount?: number;
  readonly lastRenderInputSceneBuildDurationMs?: number | null;
  readonly renderInputSceneBuildDurationSampleCount?: number;
  readonly lastRenderInputScaffoldBuildDurationMs?: number | null;
  readonly renderInputScaffoldBuildDurationSampleCount?: number;
  readonly lastRenderInputClippingBuildDurationMs?: number | null;
  readonly renderInputClippingBuildDurationSampleCount?: number;
  readonly lastScheduledFrameDurationMs?: number | null;
  readonly scheduledFrameDurationSampleCount?: number;
  readonly canvasWidth: number;
  readonly canvasHeight: number;
  readonly devicePixelRatio: number;
};
